name: commit

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm ci
        run: |
          npm ci

      - name: generate version text
        run: |
          $APP_NAME=cat .\release\app\package.json | jq -r '.name'
          $APP_VERSION=cat .\release\app\package.json | jq -r '.version'
          $GIT_HASH=git rev-parse --short HEAD
          echo -n "$APP_NAME $APP_VERSION ($GIT_HASH)" | Out-File -FilePath  .\assets\version.txt -Encoding utf8
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .\assets\version.txt
          git commit --author=. -m '[skip ci] generate version text'
          git push

      - name: package
        run: |
          $APP_NAME=cat .\release\app\package.json | jq -r '.name'
          $APP_VERSION=cat .\release\app\package.json | jq -r '.version'
          $GIT_HASH=git rev-parse --short HEAD
          echo -n "$APP_NAME $APP_VERSION ($GIT_HASH)" | Out-File -FilePath  .\assets\version.txt -Encoding utf8
          npm run postinstall
          npm run package

      - name: publish
        uses: actions/upload-artifact@v3
        with:
          name: vrc-photo-viewer
          path: ./release/build/*.exe
